"""update inquiry table

Revision ID: 09ac42cc65d0
Revises: 3bf3688d8c40
Create Date: 2026-06-20 11:51:24.405346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '09ac42cc65d0'
down_revision: Union[str, Sequence[str], None] = '3bf3688d8c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiries', sa.Column('class_id', sa.Integer(), nullable=False))
    op.drop_column('inquiries', 'class_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiries', sa.Column('class_name', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('inquiries', 'class_id')
    # ### end Alembic commands ###
