//Login Action Types
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS" 
export const LOGIN_FAILURE = "LOGIN_FAILURE"

//Dashboard Action Types
export const FETCH_DASHBOARD_STAT_REQUEST = "FETCH_DASHBOARD_STAT_REQUEST"
export const FETCH_DASHBOARD_STAT_SUCCESS = "FETCH_DASHBOARD_STAT_SUCCESS" 
export const FETCH_DASHBOARD_STAT_FAILURE = "FETCH_DASHBOARD_STAT_FAILURE"

//Classes Action Types
export const FETCH_CLASSES_REQUEST = "FETCH_CLASSES_REQUEST"
export const FETCH_CLASSES_SUCCESS = "FETCH_CLASSES_SUCCESS" 
export const FETCH_CLASSES_FAILURE = "FETCH_CLASSES_FAILURE"

// Student Action Types 
export const ADD_STUDENT_REQUEST = 'ADD_STUDENT_REQUEST';
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS';
export const ADD_STUDENT_FAILURE = 'ADD_STUDENT_FAILURE';

export const FETCH_STUDENTS_REQUEST = 'FETCH_STUDENTS_REQUEST';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAILURE = 'FETCH_STUDENTS_FAILURE';

export const UPDATE_STUDENT_REQUEST = 'UPDATE_STUDENT_REQUEST';
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_FAILURE = 'UPDATE_STUDENT_FAILURE';

export const DELETE_STUDENT_REQUEST = 'DELETE_STUDENT_REQUEST';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAILURE = 'DELETE_STUDENT_FAILURE';

// Enquiry Action Types
export const ADD_ENQUIRY_REQUEST = 'ADD_ENQUIRY_REQUEST';
export const ADD_ENQUIRY_SUCCESS = 'ADD_ENQUIRY_SUCCESS';
export const ADD_ENQUIRY_FAILURE = 'ADD_ENQUIRY_FAILURE';

export const FETCH_ENQUIRIES_REQUEST = 'FETCH_ENQUIRIES_REQUEST';
export const FETCH_ENQUIRIES_SUCCESS = 'FETCH_ENQUIRIES_SUCCESS';
export const FETCH_ENQUIRIES_FAILURE = 'FETCH_ENQUIRIES_FAILURE';

export const UPDATE_ENQUIRY_REQUEST = 'UPDATE_ENQUIRY_REQUEST';
export const UPDATE_ENQUIRY_SUCCESS = 'UPDATE_ENQUIRY_SUCCESS';
export const UPDATE_ENQUIRY_FAILURE = 'UPDATE_ENQUIRY_FAILURE';

export const DELETE_ENQUIRY_REQUEST = 'DELETE_ENQUIRY_REQUEST';
export const DELETE_ENQUIRY_SUCCESS = 'DELETE_ENQUIRY_SUCCESS';
export const DELETE_ENQUIRY_FAILURE = 'DELETE_ENQUIRY_FAILURE';

// Admission Action Types
export const ADD_ADMISSION_REQUEST = 'ADD_ADMISSION_REQUEST';
export const ADD_ADMISSION_SUCCESS = 'ADD_ADMISSION_SUCCESS';
export const ADD_ADMISSION_FAILURE = 'ADD_ADMISSION_FAILURE';

export const FETCH_ADMISSIONS_REQUEST = 'FETCH_ADMISSIONS_REQUEST';
export const FETCH_ADMISSIONS_SUCCESS = 'FETCH_ADMISSIONS_SUCCESS';
export const FETCH_ADMISSIONS_FAILURE = 'FETCH_ADMISSIONS_FAILURE';

export const UPDATE_ADMISSION_REQUEST = 'UPDATE_ADMISSION_REQUEST';
export const UPDATE_ADMISSION_SUCCESS = 'UPDATE_ADMISSION_SUCCESS';
export const UPDATE_ADMISSION_FAILURE = 'UPDATE_ADMISSION_FAILURE';

export const DELETE_ADMISSION_REQUEST = 'DELETE_ADMISSION_REQUEST';
export const DELETE_ADMISSION_SUCCESS = 'DELETE_ADMISSION_SUCCESS';
export const DELETE_ADMISSION_FAILURE = 'DELETE_ADMISSION_FAILURE';

// Web Admission Action Types
export const FETCH_WEB_ADMISSIONS_REQUEST = 'FETCH_WEB_ADMISSIONS_REQUEST';
export const FETCH_WEB_ADMISSIONS_SUCCESS = 'FETCH_WEB_ADMISSIONS_SUCCESS';
export const FETCH_WEB_ADMISSIONS_FAILURE = 'FETCH_WEB_ADMISSIONS_FAILURE';

export const DELETE_WEB_ADMISSION_REQUEST = 'DELETE_WEB_ADMISSION_REQUEST';
export const DELETE_WEB_ADMISSION_SUCCESS = 'DELETE_WEB_ADMISSION_SUCCESS';
export const DELETE_WEB_ADMISSION_FAILURE = 'DELETE_WEB_ADMISSION_FAILURE';

// Fees Action Types
export const ADD_FEE_REQUEST = 'ADD_FEE_REQUEST';
export const ADD_FEE_SUCCESS = 'ADD_FEE_SUCCESS';
export const ADD_FEE_FAILURE = 'ADD_FEE_FAILURE';

export const FETCH_FEES_REQUEST = 'FETCH_FEES_REQUEST';
export const FETCH_FEES_SUCCESS = 'FETCH_FEES_SUCCESS';
export const FETCH_FEES_FAILURE = 'FETCH_FEES_FAILURE';

export const UPDATE_FEE_REQUEST = 'UPDATE_FEE_REQUEST';
export const UPDATE_FEE_SUCCESS = 'UPDATE_FEE_SUCCESS';
export const UPDATE_FEE_FAILURE = 'UPDATE_FEE_FAILURE';